//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/New Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""KeyboardMain"",
            ""id"": ""da53a74b-766e-4a69-8c1a-36a45177888a"",
            ""actions"": [
                {
                    ""name"": ""EndGame"",
                    ""type"": ""Button"",
                    ""id"": ""12c1391a-dca7-4c80-8816-3f829e9ec180"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7f5fe550-0bdc-4f45-9c43-9c6c0632f68c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EndGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // KeyboardMain
        m_KeyboardMain = asset.FindActionMap("KeyboardMain", throwIfNotFound: true);
        m_KeyboardMain_EndGame = m_KeyboardMain.FindAction("EndGame", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KeyboardMain
    private readonly InputActionMap m_KeyboardMain;
    private List<IKeyboardMainActions> m_KeyboardMainActionsCallbackInterfaces = new List<IKeyboardMainActions>();
    private readonly InputAction m_KeyboardMain_EndGame;
    public struct KeyboardMainActions
    {
        private @NewControls m_Wrapper;
        public KeyboardMainActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @EndGame => m_Wrapper.m_KeyboardMain_EndGame;
        public InputActionMap Get() { return m_Wrapper.m_KeyboardMain; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardMainActions set) { return set.Get(); }
        public void AddCallbacks(IKeyboardMainActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardMainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardMainActionsCallbackInterfaces.Add(instance);
            @EndGame.started += instance.OnEndGame;
            @EndGame.performed += instance.OnEndGame;
            @EndGame.canceled += instance.OnEndGame;
        }

        private void UnregisterCallbacks(IKeyboardMainActions instance)
        {
            @EndGame.started -= instance.OnEndGame;
            @EndGame.performed -= instance.OnEndGame;
            @EndGame.canceled -= instance.OnEndGame;
        }

        public void RemoveCallbacks(IKeyboardMainActions instance)
        {
            if (m_Wrapper.m_KeyboardMainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKeyboardMainActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardMainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardMainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KeyboardMainActions @KeyboardMain => new KeyboardMainActions(this);
    public interface IKeyboardMainActions
    {
        void OnEndGame(InputAction.CallbackContext context);
    }
}
